### PR TITLE
Add default label set and README

### PR DESCRIPTION
**Pull request by jcbpl**
The team working on [Pages](https://github.com/cityofaustin/pages) has started to integrate GitHub Issues into our workflow, which led me to the realization that City projects could probably benefit from some standardization around the way we use GitHub labels on issues and pull requests.

GitHub doesn't have a native way to set organization-wide label defaults (at least not yet), so the best-available workaround is to use a tool like [git-labelmaker](https://github.com/himynameisdave/git-labelmaker) (or its dependency, [git-label](https://github.com/jasonbellamy/git-label)) to programmatically manage a repo's labels through the GitHub API.

As for the labels I've added to the default set, they're just a starting point (see them in action [here](https://github.com/cityofaustin/pages/issues)). I borrowed the pattern (see the image below) from [a blog post](https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/) by Zach Dunn at Robin, but I'm sure we'll want to change and evolve it over time. Suggestions welcome!

robin-github-issue-tag-system

### CODE REVIEW

**Comment by jcbpl** [comment]
@benguhin @josedigital @mattlangan

**Comment by jcbpl** [comment]
I wonder if it might make more sense to name this label set "application" or "code" or something along those lines, because I think we're going to need different sets for doc/editorial processes. These defaults probably don't even make much sense for this repo, for instance.

**Comment by jcbpl** [comment]
Or we could have a single set for everything `¯\_(ツ)_/¯`

**Comment by lovemecomputer** [comment]
cool! should add a research tag if possible since we have so much research :)

**Comment by haileypate** [comment]
Hey y'all! Are these labels intended for use outside fellow-driven repos at CoA?

If so, let's set up some time to discuss how other CoA github users can get involved in the design process. Next Wednesday's 9am meeting about GitHub standards may be a good time [😉]

**Comment by haileypate** [comment]
Alternatively, consider a prefix to the name of this repo to clarify intended audience

We're onboarding lots of new users to GitHub across the City, many of whom are non-technical. I think clear documentation at the organization level -- in this case, the names of repos -- will help newer folks understand what's directed at them and what's not.

**Comment by jcbpl** [comment]
Yep, this is definitely intended to be a city-wide resource! We can certainly talk about involving other users at the meeting on Wednesday—I personally think GitHub is a good place to collaborate on how we use GitHub (like we're doing right now).

And again, the set of labels proposed here isn't meant to be definitive—just a starting point—and the idea is that we could end up having more than one set to meet the needs of different use cases and audiences.

**Comment by haileypate** [comment]
Great! My early feedback has been submitted as #3

**Pull request closed without merging**
